# Welcome to the world of Python!
### In this notebook, we will walk through basics of coding in Python to get you started. 
### Here is a good beginer tutorial for reference: https://python101.pythonlibrary.org/index.html



## 1. Strings

In [3]:
print("Hello Python!")

Hello Python!


In [19]:
string1 = "Geostatistics"

# print(string1)

string2 = " is fun" 

## How do we combine the two strings in to a new one named string3?

string3 = string1 + string2
print(string3)

## How do we take a slice of string 3 and put it into a new string named string4?

## String slicing

string4 = string3[17:20]
string4 = string3[-3:]

print(string4)

#string5 = string3[0:13]
#print(string5)

Geostatistics is fun
fun


## 2. Lists

In [30]:
# Lists
list0 = []
list1 = [4,7,3]
list2 = ['a','b','c']


## List concatenation

list_combo = list1 + list2
print(list_combo)

## List slicing

list_sliced = list_combo[3]
# list_sliced = list_combo[-3]

print(list_sliced)
# print(combo_list)

## List sorting

list1.sort()
print(list1[::-1])



[4, 7, 3, 'a', 'b', 'c']
a
[7, 4, 3]


## 3. Numbers

In [44]:
## Integer
a = 3
print(type(a))

## Float
b = 11.0
print(type(b))

## Arithmetic Operators
c = 2

# r1 = a + b; print(r1)
# r2 = a - b; print(r2)
# r3 = a * b; print(r3)
# r4 = a/c; print(r4)
# r5 = a//c; print(r5)
# r6 = a**c; print(r6)

## Assignment Operators
a += 1 # a = a + 1
print(a)
c *= 2 # c = c*2
print(c)

## Number to string
day = 26
day_str = str(day); print(type(day_str))
month = 'Aug'

print(month+" "+day_str)

## String to number 
day_num = float(day_str)
print(day_num, type(day_num))



<class 'int'>
<class 'float'>
4
4
<class 'str'>
Aug 26
26.0 <class 'float'>


## 4. Numpy arrays

In [4]:
## Let's import your first python package
import numpy as np

## 1-D array
A1 = np.array([1,2,3]) # 1-D array
print(A1[1:2])

## How to find out the shape or dimension of the array?
print(A1.shape)


## 2-D array
B1 = np.array([[1,2,3],[4,5,6]]) 
# print(B1)
# print(B1.shape)

print(np.mean(B1,axis=1))



## Broadcasting
A2 = A1+2
print(A1)
print(A2)



## Array multiplication. Let's multiply the two arrays A1 and A2 and put the result into A3.
A3 = A1*A2
print(A3)

# Matrix product. Matrix product is different from array multiplication

C1 = np.dot(A1,np.transpose(A2))
print(C1)


[2]
(3,)
[2. 5.]
[1 2 3]
[3 4 5]
[ 3  8 15]
26


## 5. Conditional statements

In [29]:
## An example of if, else
var1 = 10
var2 = 3

## Create a boolean variable that indicates whether a condition is true or false

flag = var1 > var2
# print(flag)


## Write our first if-else statement 

# if var1>var2:
#     print(str(var1)+" is greater than "+str(var2))
# else:
#     print(str(var1)+" is not greater than "+str(var2))
    
    
## An example of elif, and, or
a = 3
b = 11.0

# if a<10 and b<10:
#     print("Both are less than 10")
# elif a<10 or b<10:
#     print("One of the two is less than 10")
# else:
#     print("None is less than 10")

print(A1,A3)
print((A1<10)*1)
print((A3<10)*1)

print(((A1<10)+(A3<10))*1)
    

## More about Boolean Operations
A1 = np.array([1,2,3]) # 1-D array

print(A1!=2)
print(A1==2)


my_list = [1, 2, 3, 4]
x = 3

if x not in my_list:
    print('yes')
else:
    print('no')

## Write a conditional statement to find out if "x" is in "my_list".
## in / not in, equal, not equal



[1 2 3] [ 3  8 15]
[1 1 1]
[1 1 0]
[1 1 1]
[ True False  True]
[False  True False]
no


## 6. For loops

In [34]:
## Loop over a list

my_list2 = ['a','b','c']

## Loop over a numerical range

for item in my_list2:
    print(item)

## Enumerate
# for i in range(13):
#     print(i)

## list, enumerate

for i,fname in enumerate(my_list2):
    print(i,fname)
    

## Combine loops and conditional statements
my_list = [1, 2, 3, 4]

for i in my_list:
    if i>2:
        print(i)


a
b
c
0 a
1 b
2 c
3
4


## 7. List Comprehensions

In [39]:
## Create a list where the ith item equals to i+3
my_list2 = []

for i in range(5):
    my_list2.append(i+3)
#     print(my_list2)

#equivalent to:
my_list2 = [i+3 for i in range(5)]
print(my_list2)

# print(my_list2)

## Create a list where each item is the second character of each item in "my_list3", i.e., "b" in "ab".
my_list3 = ['ab', 'cd', 'ef', 'gh', 'ij']
my_list4 = [item[1] for item in my_list3]
print(my_list4)



[3, 4, 5, 6, 7]
['b', 'd', 'f', 'h', 'j']


## 8. Work with files

In [43]:
## work with files
import os # operating system
filename = "test.txt"

## check if a file exists
print(os.path.isfile(filename))


## open and read a text file
with open(filename,'r') as f:
    line1 = f.read()
print(line1)


## open and write a text file    
# with open(filename,'w') as f:
#     f.write('Geostatistics is fun.')



True
Geostatistics is fun.


## 9. Functions

In [10]:
## Define a function to calculate the maximum amount of water vapor in the air under given temperature
import numpy as np
def T2ES(T):
    # T in degree C
    # esat in kPa
    esat = 0.611*np.exp(17.625*T/(T+243.04))
    return esat

## Call the function to calculate esat under T=20
esat1 = T2ES(20)
   

## Call the function to calculate esat under temperatures ranging from 0 to 30 degree C



## 10. Plot lines

In [11]:
import matplotlib.pyplot as plt # The standard package for visualization

# plt.figure()
# plt.plot(T,esat2)
# plt.xlabel('Temperature (degree C)')
# plt.ylabel('Saturated vapor pressure (kPa)')
