# Welcome to the world of Python!
### In this notebook, we will walk through basics of coding in Python to get you started. 
### Here is a good beginer tutorial for reference: https://python101.pythonlibrary.org/index.html



## 1. Strings

In [5]:
# P
print("Hello Python!")



Hello Python!


In [32]:
string1 = "Geostatistics"

# print(string1)

string2 = " is " 

## How do we combine the two strings in to a new one named string3?

string3 = string1 + string2
print(string3)

## How do we take a slice of string 3 and put it into a new string named string4?

## String slicing

string4 = string2[-3:]

print(string4)

## Know that 0 is first number and 12 is the last that, marks the index position 

string5 = string3[17:]
print(string5)



Geostatistics is 
is 



## 2. Lists

In [50]:
# Lists
#Recall ZERO is the first digit counted by Python
## List0 is empty (a place holder)
list0 = []
list1 = [4,7,3]
list2 = ['a','b','c']


## List concatenation

combo_list = list1+list2 
print(combo_list)

## List slicing

list_sliced = combo_list[3]
print(list_sliced)

## List sorting

list1.sort()
print(list1)

#Change order from ascending to decending 
list2.sort()
print(list2)
print(list1([::-1])

SyntaxError: invalid syntax (1515087219.py, line 26)

## 3. Numbers

In [72]:
## Integer
a = 3

# Identifies input typ, integer, matrix, list
print(type(a))

## Float
b = 11.0
print(type(b))

## Arithmetic Operators
c = 2

# r1 = a + b; print(r1)
# ## Assignment Operators
# r2 = a + b; print(r2)
# r3 = a - b; print(r3)
# r4 = a * b; print(r4)
# r5 = a / c; print(r5)
# r6 = a//c; print(r6)
# r7 = a**c; print(r7)

## FOR FOR LOOPS REVIEW THE FOLLOWING
# a = a + 1
a+= 1


## Number to string
day = 26
day_str = str(day); print(type(day_str))
month = 'Aug'
date = month + day_str; print(date)

## String to number 
day_num = float(day_str)
print(day_num);


<class 'int'>
<class 'float'>
<class 'str'>
Aug26


## 4. Numpy arrays

In [103]:
## Let's import your first python package

## Designate Numpy variable as np
import numpy as np
## Cannot have two seperate data 
## 1-D array, ".array" calls for the array
A1 = np.array([1,2,3]) # 1-D array

print(A1[1])
print(A1[1:2])
## How to find out the shape or dimension of the array?
print(A1.shape)

## Wheb running a geospatial analysis, we will return
## 2-D array; [] first row, [] second row
# Displays the configuration of rows and columns
B1 = np.array([[1,2,3],[4,5,6]]) 
print(B1.shape)

# Calculates the averages accross a rows
print(np.mean(B1,axis=0))
print(np.mean(B1,axis=1))
## Broadcasting
## Have a scaler value 
A2 = A1+2
print(A2)

A3 = A1*A2;print(A3)
## Array multiplication. Let's multiply the two arrays A1 and A2 and put the result into A3.
# A3 = 

# Matrix product. Matrix product is different from array multiplication

C1 = np.dot(A1,np.transpose(A2))
print(C1)

2
[2]
(3,)
(2, 3)
[2.5 3.5 4.5]
[2. 5.]
[3 4 5]
[ 3  8 15]
26


## 5. Conditional statements

In [146]:
## An example of if, else
var1 = 1
var2 = 3

## Create a boolean variable that indicates whether a condition is true or false (two possible outcomes/binary output)

#flag = var1>var2; print(flag)

## Write our first if-else statement 

#if var1>var:
#print(str(var1)("is greater than"+str(var2))
    
    #  else: var1<var2
#print(str(var1)("is not greater than"+str(var2))

    
## An example of elif, and, or
a = 3
b = 11.0

#if a<10 and b<10:
#print("a less than 10, b less than 10")   
#elif a<10 or b<10:
#   print("a less than 10 or b less than 10"
#else:
#    print("none less than 10")

print(A1,A3)
print((A1<10)+(A3<10))
# Allows you to see the Boolean (0,1) binary
print(((A1<10)+(A3<10))*1)
## More about Boolean Operations
A1 = np.array([1,2,3]) # 1-D array

  
print(A1!=2)
print(A1==2)
  # == explicit designation to equal this varible


my_list = [1, 2, 3, 4]
x = 3

if x in my_list:
    print('yes')
else:
    print('no')
## Write a conditional statement to find out if "x" is in "my_list".
## in / not in, equal, not equal



[1 2 3] [ 3  8 15]
[ True  True  True]
[1 1 1]
[ True False  True]
[False  True False]
yes


## 6. For loops

In [181]:
## Loop over a list

my_list2 = ['a','b','c']

## Loop over a numerical range, allows for iterations in model design (time steps)

#for item in my_list2:
   # print(item)

#for i in range(13):
    #print(i)

## Enumerate, how to create a list of file names in a folder

## list, enumerate

for i,fname in enumerate(my_list2):
    print(i,fname)

## Combine loops and conditional statements
my_list = [1, 2, 3, 4]

for i in my_list:
    if i>2:
        print(i)
#else:
 #   print('no')


0 a
1 b
2 c
3
4


## 7. List Comprehensions

In [185]:
## Create a list where the ith item equals to i+3
my_list2 = []

for i in range(5):
    my_list2.append(i+3)
    print(my_list2) # When including inside of the for loop, shoWS ALL steps
#Equivalent to:
my_list2 = [i+3 for i in range(5)]
print(my_list2)


## Create a list where each item is the second character of each item in "my_list3", i.e., "b" in "ab".bbfj
my_list3 = ['ab', 'cd', 'ef', 'gh', 'ij']



[3]
[3, 4]
[3, 4, 5]
[3, 4, 5, 6]
[3, 4, 5, 6, 7]
[3, 4, 5, 6, 7]


## 8. Work with files

In [201]:
## work with files
import os # operating system, check if a file exists in a current directory
filename = "test.txt"

## check if a file exists
print(os.path.isfile(filename))


with open(filename,'w') as f: #Gives permission to 'write' file
#    f.write('Geostatistics is fun')
## open and read a text file
with open(filename,'r') as f:
        line1 = f.read()
print(line1)
## open and write a text file    



IndentationError: expected an indented block after 'with' statement on line 9 (4101011311.py, line 12)

## 9. Functions

In [10]:
## Define a function to calculate the maximum amount of water vapor in the air under given temperature
import numpy as np
def T2ES(T):
    # T in degree C
    # esat in kPa
    esat = 0.611*np.exp(17.625*T/(T+243.04))
    return esat

## Call the function to calculate esat under T=20
esat1 = T2ES(20)
   

## Call the function to calculate esat under temperatures ranging from 0 to 30 degree C



## 10. Plot lines

In [11]:
import matplotlib.pyplot as plt # The standard package for visualization

# plt.figure()
# plt.plot(T,esat2)
# plt.xlabel('Temperature (degree C)')
# plt.ylabel('Saturated vapor pressure (kPa)')
